---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: Estas perguntas frequentes podem ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre a classificação de dados da NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Estas perguntas frequentes podem ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta.



== Classificação de dados da NetApp

As perguntas a seguir fornecem uma compreensão geral da Classificação de Dados.



=== Como funciona a Classificação de Dados?

A Classificação de Dados implanta outra camada de IA junto com seu sistema NetApp Console e sistemas de armazenamento.  Em seguida, ele verifica os dados em volumes, buckets, bancos de dados e outras contas de armazenamento e indexa os insights de dados encontrados.  A classificação de dados utiliza inteligência artificial e processamento de linguagem natural, ao contrário de soluções alternativas que são comumente criadas em torno de expressões regulares e correspondência de padrões.

A classificação de dados usa IA para fornecer compreensão contextual dos dados para detecção e classificação precisas.  Ele é impulsionado pela IA porque foi projetado para tipos de dados e escala modernos.  Ele também entende o contexto dos dados para fornecer descoberta e classificação fortes e precisas.

link:concept-classification.html["Saiba mais sobre como funciona a Classificação de Dados"] .



=== O Data Classification tem uma API REST e funciona com ferramentas de terceiros?

Sim, o Data Classification tem uma API REST para os recursos suportados na versão do Data Classification que faz parte da plataforma principal do Console. Ver link:api-classification.html["Documentação do API"] .



=== A classificação de dados está disponível nos mercados de nuvem?

A Classificação de Dados faz parte dos principais recursos do NetApp Console, portanto você não precisa usar os marketplaces para este serviço.



== Classificação de dados, digitalização e análise

As perguntas a seguir estão relacionadas ao desempenho da varredura de classificação de dados e à análise.



=== Com que frequência a Classificação de Dados verifica meus dados?

Embora a verificação inicial dos seus dados possa demorar um pouco, as verificações subsequentes apenas inspecionam as alterações incrementais, o que reduz o tempo de verificação do sistema.  A Classificação de Dados verifica seus dados continuamente em rodízio, seis repositórios por vez, para que todos os dados alterados sejam classificados muito rapidamente.

link:task-scanning-overview.html["Aprenda como funcionam as varreduras"] .

A Classificação de Dados verifica os bancos de dados apenas uma vez por dia; os bancos de dados não são verificados continuamente como outras fontes de dados.

As varreduras de dados têm um impacto insignificante em seus sistemas de armazenamento e em seus dados.



=== O desempenho da digitalização varia?

O desempenho da verificação pode variar com base na largura de banda da rede e no tamanho médio dos arquivos no seu ambiente.  Também pode depender das características de tamanho do sistema host (na nuvem ou no local). Consulte link:concept-classification.html["A instância de classificação de dados"] e link:task-deploy-overview.html["Implementando a Classificação de Dados"] para maiores informações.

Ao adicionar inicialmente novas fontes de dados, você também pode optar por executar apenas uma verificação de "mapeamento" (Mapping only) em vez de uma verificação de "classificação" completa (Map & Classify).  O mapeamento pode ser feito em suas fontes de dados muito rapidamente porque ele não acessa arquivos para ver os dados dentro deles. link:task-scanning-overview.html["Veja a diferença entre um mapeamento e uma varredura de classificação"] .



=== Posso pesquisar meus dados usando a Classificação de Dados?

A Classificação de Dados oferece amplos recursos de pesquisa que facilitam a busca por um arquivo ou dado específico em todas as fontes conectadas.  A classificação de dados permite que os usuários pesquisem mais profundamente do que apenas o que os metadados refletem.  É um serviço independente de idioma que também pode ler os arquivos e analisar uma infinidade de tipos de dados confidenciais, como nomes e IDs.  Por exemplo, os usuários podem pesquisar em armazenamentos de dados estruturados e não estruturados para encontrar dados que podem ter vazado de bancos de dados para arquivos de usuários, violando a política corporativa.  As pesquisas podem ser salvas para mais tarde, e políticas podem ser criadas para pesquisar e agir sobre os resultados em uma frequência definida.

Depois que os arquivos de interesse forem encontrados, as características podem ser listadas, incluindo tags, conta do sistema, bucket, caminho do arquivo, categoria (da classificação), tamanho do arquivo, última modificação, status de permissão, duplicatas, nível de sensibilidade, dados pessoais, tipos de dados sensíveis dentro do arquivo, proprietário, tipo de arquivo, tamanho do arquivo, hora de criação, hash do arquivo, se os dados foram atribuídos a alguém que busca sua atenção e muito mais.  Filtros podem ser aplicados para filtrar características que não são pertinentes.

A Classificação de Dados também tem controle de acesso baseado em função (RBAC) para permitir que arquivos sejam movidos ou excluídos, se as permissões corretas estiverem presentes.  Se as permissões corretas não estiverem presentes, as tarefas podem ser atribuídas a alguém na organização que tenha as permissões corretas.



== Gestão e privacidade de classificação de dados

As perguntas a seguir fornecem informações sobre como gerenciar a Classificação de Dados e as configurações de privacidade.



=== Como habilitar ou desabilitar a Classificação de Dados?

Primeiro, você precisa implantar uma instância do Data Classification no Console ou em um sistema local.  Depois que a instância estiver em execução, você poderá habilitar o serviço em sistemas, bancos de dados e outras fontes de dados existentes na guia *Configuração* ou selecionando um sistema específico. link:task-getting-started-compliance.html["Aprenda como começar"] .


NOTE: A ativação da Classificação de Dados em uma fonte de dados resulta em uma verificação inicial imediata.  Os resultados da verificação serão exibidos logo em seguida.

Você pode desabilitar a Classificação de Dados para verificar um sistema individual, banco de dados ou grupo de compartilhamento de arquivos na página Configuração de Classificação de Dados. Ver link:task-managing-compliance.html["Remover fontes de dados da Classificação de Dados"] .

Para remover completamente a instância de Classificação de Dados, remova-a manualmente do portal do seu provedor de nuvem ou do local local.



=== O serviço pode excluir dados de digitalização em determinados diretórios?

Sim. Se você quiser que a Classificação de Dados exclua dados de digitalização que residem em determinados diretórios de fonte de dados, você pode fornecer essa lista ao mecanismo de classificação.  Depois de aplicar essa alteração, a Classificação de Dados excluirá os dados de digitalização nos diretórios especificados. link:task-exclude-scan-paths.html["Saber mais"] .



=== Os snapshots que residem em volumes ONTAP são verificados?

Não. A Classificação de Dados não verifica instantâneos porque o conteúdo é idêntico ao conteúdo do volume.



=== O que acontece se a hierarquização de dados estiver habilitada nos seus volumes ONTAP ?

Quando a Classificação de Dados verifica volumes que têm dados frios em camadas para armazenamento de objetos usando as verificações Somente mapeamento, ela verifica todos os dados — dados que estão em discos locais e dados frios em camadas para armazenamento de objetos.  Isso também é válido para produtos que não são da NetApp e que implementam camadas.

A varredura somente de mapeamento não aquece os dados frios; eles permanecem frios e armazenados no armazenamento de objetos.  Por outro lado, se você executar a verificação Map & Classify, algumas configurações podem aquecer os dados frios.



== Tipos de sistemas de origem e tipos de dados

As perguntas a seguir estão relacionadas aos tipos de armazenamento que podem ser digitalizados e aos tipos de dados que são digitalizados.



=== Há alguma restrição quando implantado em uma região governamental?

A classificação de dados é suportada quando o agente do Console é implantado em uma região governamental (AWS GovCloud, Azure Gov ou Azure DoD), também conhecido como "modo restrito".



=== Quais fontes de dados posso escanear se instalar o Data Classification em um site sem acesso à Internet?


IMPORTANT: O modo privado BlueXP (interface BlueXP legada) normalmente é usado com ambientes locais que não têm conexão com a Internet e com regiões de nuvem seguras, o que inclui AWS Secret Cloud, AWS Top Secret Cloud e Azure IL6. A NetApp continua a oferecer suporte a esses ambientes com a interface legada BlueXP . Para documentação do modo privado na interface BlueXP legada, consultelink:https://docs.netapp.com/us-en/console-setup-admin/media/BlueXP-Private-Mode-legacy-interface.pdf["Documentação em PDF para o modo privado do BlueXP"^] .

A Classificação de Dados só pode escanear dados de fontes de dados locais no site local.  Neste momento, a Classificação de Dados pode escanear as seguintes fontes de dados locais no "modo privado" — também conhecido como site "escuro":

* Sistemas ONTAP locais
* Esquemas de banco de dados
* Armazenamento de objetos que usa o protocolo Simple Storage Service (S3)




=== Quais tipos de arquivo são suportados?

A Classificação de Dados verifica todos os arquivos em busca de insights de categoria e metadados e exibe todos os tipos de arquivo na seção de tipos de arquivo do painel.

Quando a Classificação de Dados detecta Informações Pessoais Identificáveis (PII) ou quando realiza uma pesquisa DSAR, somente os seguintes formatos de arquivo são suportados:

`+.CSV, .DCM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== Que tipos de dados e metadados a Classificação de Dados captura?

A Classificação de Dados permite que você execute uma verificação geral de "mapeamento" ou uma verificação completa de "classificação" em suas fontes de dados.  O mapeamento fornece apenas uma visão geral de alto nível dos seus dados, enquanto a classificação fornece uma varredura profunda dos seus dados.  O mapeamento pode ser feito em suas fontes de dados muito rapidamente porque ele não acessa arquivos para ver os dados dentro deles.

* *Verificação de mapeamento de dados (Verificação somente de mapeamento)*: A classificação de dados verifica apenas os metadados.  Isso é útil para gerenciamento e governança geral de dados, definição rápida de escopo de projetos, grandes propriedades e priorização.  O mapeamento de dados é baseado em metadados e é considerado uma varredura *rápida*.
+
Após uma verificação rápida, você pode gerar um Relatório de Mapeamento de Dados.  Este relatório é uma visão geral dos dados armazenados em suas fontes de dados corporativos para ajudar você a tomar decisões sobre utilização de recursos, migração, backup, segurança e processos de conformidade.

* *Verificação profunda de classificação de dados (verificação de mapa e classificação)*: a classificação de dados verifica os dados usando protocolos padrão e permissão somente leitura em todos os seus ambientes.  Arquivos selecionados são abertos e verificados em busca de dados comerciais confidenciais, informações privadas e problemas relacionados a ransomware.
+
Após uma verificação completa, há muitos recursos adicionais de Classificação de Dados que você pode aplicar aos seus dados, como visualizar e refinar dados na página Investigação de Dados, pesquisar nomes em arquivos, copiar, mover e excluir arquivos de origem e muito mais.



A Classificação de Dados captura metadados como: nome do arquivo, permissões, hora de criação, último acesso e última modificação.  Isso inclui todos os metadados que aparecem na página Detalhes da Investigação de Dados e nos Relatórios de Investigação de Dados.

A classificação de dados pode identificar muitos tipos de dados privados, como informações pessoais (PII) e informações pessoais sensíveis (SPII). Para obter detalhes sobre dados privados, consultexref:reference-private-data-categories.html[Categorias de dados privados que a Classificação de Dados verifica] .



=== Posso limitar as informações de Classificação de Dados a usuários específicos?

Sim, a Classificação de Dados é totalmente integrada ao NetApp Console.  Os usuários do NetApp Console só podem ver informações dos sistemas que eles têm permissão para visualizar, de acordo com suas permissões.

Além disso, se você quiser permitir que determinados usuários apenas visualizem os resultados da verificação de Classificação de Dados sem ter a capacidade de gerenciar as configurações de Classificação de Dados, você pode atribuir a esses usuários a função *Visualizador de classificação* (ao usar o NetApp Console no modo padrão) ou a função *Visualizador de conformidade* (ao usar o NetApp Console no modo restrito). link:concept-classification.html["Saber mais"] .



=== Alguém pode acessar os dados privados enviados entre meu navegador e a Classificação de Dados?

Não. Os dados privados enviados entre seu navegador e a instância de Classificação de Dados são protegidos com criptografia de ponta a ponta usando TLS 1.2, o que significa que partes da NetApp e não da NetApp não podem lê-los.  A Classificação de Dados não compartilhará nenhum dado ou resultado com a NetApp , a menos que você solicite e aprove o acesso.

Os dados digitalizados permanecem no seu ambiente.



=== Como os dados confidenciais são tratados?

O NetApp não tem acesso a dados confidenciais e não os exibe na interface do usuário.  Dados confidenciais são mascarados, por exemplo, os últimos quatro números são exibidos para informações de cartão de crédito.



=== Onde os dados são armazenados?

Os resultados da verificação são armazenados no Elasticsearch dentro da sua instância de Classificação de Dados.



=== Como os dados são acessados?

A Classificação de Dados acessa dados armazenados no Elasticsearch por meio de chamadas de API, que exigem autenticação e são criptografadas usando AES-128.  Acessar o Elasticsearch diretamente requer acesso root.



== Licenças e custos

A pergunta a seguir está relacionada ao licenciamento e aos custos para usar a Classificação de Dados.



=== Quanto custa a Classificação de Dados?

A classificação de dados é um recurso essencial do NetApp Console.  Não é cobrado.



== Implantação do agente de console

As perguntas a seguir estão relacionadas ao agente do Console.



=== O que é o agente do Console?

O agente do Console é um software executado em uma instância de computação na sua conta de nuvem ou no local, que permite que o NetApp Console gerencie com segurança os recursos da nuvem. Você deve implantar um agente do Console para usar a Classificação de Dados.



=== Onde o agente do Console precisa ser instalado?

Ao verificar dados, o agente do NetApp Console Console precisa ser instalado nos seguintes locais:

* Para Cloud Volumes ONTAP na AWS ou Amazon FSx para ONTAP: o agente do console está na AWS.
* Para Cloud Volumes ONTAP no Azure ou no Azure NetApp Files: o agente do console está no Azure.
* Para Cloud Volumes ONTAP no GCP: o agente do console está no GCP.
* Para sistemas ONTAP locais: o agente do console está local.


Se você tiver dados nesses locais, pode ser necessário usar https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["vários agentes de console"^] .



=== A Classificação de Dados requer acesso a credenciais?

A classificação de dados em si não recupera credenciais de armazenamento.  Em vez disso, eles são armazenados no agente do Console.

A Classificação de Dados usa credenciais do plano de dados, por exemplo, credenciais CIFS para montar compartilhamentos antes da digitalização.



=== A comunicação entre o serviço e o agente do Console usa HTTP?

Sim, a Classificação de Dados se comunica com o agente do Console usando HTTP.



== Implantação de classificação de dados

As perguntas a seguir estão relacionadas à instância separada de Classificação de Dados.



=== Quais modelos de implantação a Classificação de Dados suporta?

O NetApp Console permite que o usuário escaneie e gere relatórios sobre sistemas praticamente em qualquer lugar, incluindo ambientes locais, na nuvem e híbridos.  A Classificação de Dados normalmente é implantada usando um modelo SaaS, no qual o serviço é habilitado por meio da interface do Console e não requer instalação de hardware ou software.  Mesmo neste modo de implantação de clicar e executar, o gerenciamento de dados pode ser feito independentemente de os armazenamentos de dados estarem no local ou na nuvem pública.



=== Que tipo de instância ou VM é necessária para a Classificação de Dados?

Quandolink:task-deploy-cloud-compliance.html["implantado na nuvem"] :

* Na AWS, a Classificação de Dados é executada em uma instância m6i.4xlarge com um disco GP2 de 500 GiB.  Você pode selecionar um tipo de instância menor durante a implantação.
* No Azure, a Classificação de Dados é executada em uma VM Standard_D16s_v3 com um disco de 500 GiB.
* No GCP, a Classificação de Dados é executada em uma VM n2-standard-16 com um disco persistente Standard de 500 GiB.


link:concept-classification.html["Saiba mais sobre como funciona a Classificação de Dados"] .



=== Posso implantar a Classificação de Dados no meu próprio host?

Sim. Você pode instalar o software de classificação de dados em um host Linux que tenha acesso à Internet na sua rede ou na nuvem.  Tudo funciona da mesma forma e você continua gerenciando a configuração e os resultados da verificação por meio do Console.  Verlink:task-deploy-compliance-onprem.html["Implementando a Classificação de Dados no local"] para requisitos do sistema e detalhes de instalação.



=== E quanto aos sites seguros sem acesso à internet?

Sim, isso também é suportado.  Você podelink:task-deploy-compliance-dark-site.html["implantar a Classificação de Dados em um site local que não tenha acesso à Internet"] para sites completamente seguros.
