---
sidebar: sidebar 
permalink: task-active-directory.html 
keywords: active directory, ad, data sense, cloud data sense 
summary: Você pode integrar um Active Directory global com a NetApp Data Classification para aprimorar os resultados que a Classificação de Dados relata sobre proprietários de arquivos e quais usuários e grupos têm acesso aos seus arquivos. 
---
= Integrar o Active Directory com NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode integrar um Active Directory global com a NetApp Data Classification para aprimorar os resultados que a Classificação de Dados relata sobre proprietários de arquivos e quais usuários e grupos têm acesso aos seus arquivos.

Ao configurar determinadas fontes de dados (listadas abaixo), você precisa inserir credenciais do Active Directory para que a Classificação de Dados verifique os volumes CIFS.  Essa integração fornece à Classificação de Dados detalhes sobre o proprietário do arquivo e as permissões dos dados que residem nessas fontes de dados.  O Active Directory inserido para essas fontes de dados pode ser diferente das credenciais globais do Active Directory inseridas aqui.  A Classificação de Dados procurará em todos os Diretórios Ativos integrados detalhes de usuários e permissões.

Esta integração fornece informações adicionais nos seguintes locais na Classificação de Dados:

* Você pode usar o "Proprietário do Arquivo"link:task-investigate-data.html["filtro"] e veja os resultados nos metadados do arquivo no painel Investigação.  Em vez do proprietário do arquivo conter o SID (Identificador de Segurança), ele é preenchido com o nome do usuário real.
+
Você também pode visualizar mais detalhes sobre o proprietário do arquivo: nome da conta, endereço de e-mail e nome da conta SAM, ou visualizar itens de propriedade desse usuário.

* Você pode ver link:task-investigate-data.html["permissões completas de arquivo"] para cada arquivo e diretório ao selecionar o botão "Exibir todas as permissões".
* Nolink:task-controlling-governance-data.html["Painel de governança"] , o painel Permissões abertas mostrará um nível maior de detalhes sobre seus dados.



NOTE: SIDs de usuários locais e SIDs de domínios desconhecidos não são traduzidos para o nome de usuário real.



== Fontes de dados suportadas

Uma integração do Active Directory com a Classificação de Dados pode identificar dados das seguintes fontes de dados:

* Azure NetApp Files
* Cloud Volumes ONTAP
* FSx para ONTAP
* Sistemas ONTAP locais




== Conecte-se ao seu servidor Active Directory

Depois de implantar a Classificação de Dados e ativar a verificação em suas fontes de dados, você pode integrar a Classificação de Dados ao seu Active Directory.  O Active Directory pode ser acessado usando um endereço IP de servidor DNS ou um endereço IP de servidor LDAP.

As credenciais do Active Directory podem ser somente leitura, mas fornecer credenciais de administrador garante que a Classificação de Dados possa ler quaisquer dados que exijam permissões elevadas.  As credenciais são armazenadas na instância de Classificação de Dados.

Para volumes/compartilhamentos de arquivos CIFS, se você quiser garantir que os "últimos horários de acesso" dos seus arquivos permaneçam inalterados pelas verificações de Classificação de Dados, o usuário deve ter permissão de Gravação de Atributos. Se possível, recomendamos que o usuário configurado no Active Directory faça parte de um grupo pai na organização que tenha permissões para todos os arquivos.

.Requisitos
* Você deve ter um Active Directory já configurado para os usuários da sua empresa.
* Você deve ter as informações do Active Directory:
+
** Endereço IP do servidor DNS ou vários endereços IP
+
ou

+
Endereço IP do servidor LDAP ou vários endereços IP

** Nome de usuário e senha para acessar o servidor
** Nome de domínio (nome do Active Directory)
** Se você está usando LDAP seguro (LDAPS) ou não
** Porta do servidor LDAP (normalmente 389 para LDAP e 636 para LDAP seguro)


* As seguintes portas devem estar abertas para comunicação de saída pela instância de Classificação de Dados:
+
[cols="20,20,30,30"]
|===
| Protocolo | Porta | Destino | Propósito 


| TCP e UDP | 389 | Diretório ativo | LDAP 


| TCP | 636 | Diretório ativo | LDAP sobre SSL 


| TCP | 3268 | Diretório ativo | Catálogo Global 


| TCP | 3269 | Diretório ativo | Catálogo global sobre SSL 
|===


.Passos
. Em Classificação de Dados, selecione **Configuração**.
. Acesse a aba **Configurações**.
. No cabeçalho Active Directory, selecione **Adicionar**.
. Na caixa de diálogo Conectar ao Active Directory, insira os detalhes do Active Directory e selecione *Conectar*.
+
Você pode adicionar vários endereços IP, se necessário, selecionando *Adicionar IP*.

+
A Classificação de Dados é integrada ao Active Directory e uma nova seção é adicionada à página Configuração.





== Gerencie sua integração com o Active Directory

Se precisar modificar algum valor na sua integração com o Active Directory, você deve atualizar a configuração do Active Directory em Data Classification. Retorne ao menu **Configuration** em Data Classification e acesse a guia de configurações para fazer as alterações.

Você também pode excluir a integração selecionando o botão **Remover** em Active Directory.
