---
sidebar: sidebar 
permalink: task-scanning-overview.html 
keywords: cloud compliance, get started, enable cloud compliance, cifs credentials, smb credentials, cloud compliance access, privacy, compliance, dp volumes, data protection volumes, CVO, Cloud Volumes ONTAP, data sense, cloud data sense, map-only scans, map and classify, full 
summary: Analise suas fontes de dados com o NetApp Data Classification. 
---
= Digitalizar fontes de dados com a NetApp Data Classification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification examina os dados nos repositórios (os volumes, esquemas de banco de dados ou outros dados de usuário) que você seleciona para identificar dados pessoais e confidenciais. Data Classification então mapeia os dados da sua organização, categoriza cada arquivo e identifica padrões predefinidos nos dados. O resultado da análise é um índice de informações pessoais, informações pessoais confidenciais, categorias de dados e tipos de arquivo.

Após a verificação inicial, a Classificação de Dados verifica continuamente seus dados em um sistema round-robin para detectar alterações incrementais.  É por isso que é importante manter a instância em execução.

Você pode habilitar e desabilitar verificações no nível do volume ou no nível do esquema do banco de dados.



== Compreenda os tipos de digitalização

Você pode realizar dois tipos de varreduras na Classificação de Dados:

* **As varreduras somente de mapa** fornecem apenas uma visão geral de alto nível dos seus dados e são realizadas em fontes de dados selecionadas. As varreduras somente de mapa levam menos tempo do que as varreduras completas porque não acessam arquivos para ver os dados dentro deles.
* **As varreduras completas** fornecem uma análise em nível profundo dos seus dados. Uma varredura completa inclui uma varredura de mapeamento e uma classificação dos dados dentro dos arquivos.



TIP: Realizar uma varredura somente com base no mapa pode ser útil para obter uma visão geral dos seus dados e identificar áreas específicas para realizar varreduras completas.

Analise as tabelas para ver quais informações são exibidas nas varreduras somente do mapa e nas varreduras completas.

[cols="47,18,18"]
|===
| Recurso | Digitalização completa | Varredura apenas do mapa 


| Velocidade de digitalização | Lento | Rápido 


| Preços | Livre | Livre 


| Capacidade | Limitado a 500 TiB* | Limitado a 500 TiB* 


| Lista de tipos de arquivo e capacidade utilizada | Sim | Sim 


| Número de arquivos e capacidade utilizada | Sim | Sim 


| Idade e tamanho dos arquivos | Sim | Sim 


| Capacidade de executar umlink:task-controlling-governance-data.html["Relatório de Mapeamento de Dados"] | Sim | Sim 


| Página de investigação de dados para visualizar detalhes do arquivo | Sim | Não 


| Pesquisar nomes dentro de arquivos | Sim | Não 


| Criarlink:task-using-policies.html["consultas salvas"] que fornecem resultados de pesquisa personalizados | Sim | Não 


| Capacidade de executar outros relatórios | Sim | Não 


| Capacidade de ver metadados de arquivos** | Sim | Sim 
|===
{asterisk}A Classificação de Dados não impõe um limite à quantidade de dados que analisa. Cada agente do Console suporta a análise e exibição de 500 TiB de dados. Para analisar mais de 500 TiB de dados, link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#connector-installation["instalar outro agente do Console"^] em seguida link:task-deploy-overview.html["implantar outra instância de Classificação de Dados"]. + A interface do usuário do Console exibe dados de um único conector. Para obter dicas sobre como visualizar dados de vários agentes do Console, consulte link:https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["Trabalhar com vários agentes do Console"^].

{asterisco}{asterisco} Os seguintes metadados são extraídos dos arquivos durante as varreduras de mapeamento:

* Hora da descoberta do arquivo
* Último acesso ao arquivo
* Última modificação do arquivo
* Tipo de arquivo
* Tamanho do arquivo
* Criação de arquivo
* Número de arquivos
* Extração de permissões
* Repositório de armazenamento
* Sistema
* Tipo de sistema
* Capacidade utilizada


.Diferenças do painel de governança:
[%collapsible]
====
[cols="40,25,25"]
|===
| Recurso | Digitalização completa | Varredura apenas do mapa 


| Dados obsoletos | Sim | Sim 


| Dados não comerciais | Sim | Sim 


| Arquivos duplicados | Sim | Sim 


| Consultas salvas predefinidas | Sim | Não 


| Consultas salvas padrão | Sim | Sim 


| Relatório DDA | Sim | Sim 


| Relatório de mapeamento | Sim | Sim 


| Detecção do nível de sensibilidade | Sim | Não 


| Dados sensíveis com permissões amplas | Sim | Não 


| Permissões abertas | Sim | Sim 


| Era dos dados | Sim | Sim 


| Tamanho dos dados | Sim | Sim 


| Categorias | Sim | Não 


| Tipos de arquivo | Sim | Sim 
|===
====
.Diferenças do painel de conformidade:
[%collapsible]
====
[cols="40,25,25"]
|===
| Recurso | Digitalização completa | Varredura apenas do mapa 


| Informações pessoais | Sim | Não 


| Informações pessoais sensíveis | Sim | Não 


| Relatório de avaliação de risco de privacidade | Sim | Não 


| Relatório HIPAA | Sim | Não 


| Relatório PCI DSS | Sim | Não 
|===
====
.Diferenças nos filtros de investigação:
[%collapsible]
====
[cols="40,25,25"]
|===
| Recurso | Digitalização completa | Varredura apenas do mapa 


| Consultas salvas | Sim | Sim 


| Tipo de sistema | Sim | Sim 


| Sistema | Sim | Sim 


| Repositório de armazenamento | Sim | Sim 


| Tipo de arquivo | Sim | Sim 


| Tamanho do arquivo | Sim | Sim 


| Tempo criado | Sim | Sim 


| Tempo descoberto | Sim | Sim 


| Última modificação | Sim | Sim 


| Último acesso | Sim | Sim 


| Permissões abertas | Sim | Sim 


| Caminho do diretório de arquivos | Sim | Sim 


| Categoria | Sim | Não 


| Nível de sensibilidade | Sim | Não 


| Número de identificadores | Sim | Não 


| Dados pessoais | Sim | Não 


| Dados pessoais sensíveis | Sim | Não 


| Titular dos dados | Sim | Não 


| Duplicatas | Sim | Sim 


| Status de classificação | Sim | O status é sempre "Insights limitados" 


| Evento de análise de varredura | Sim | Sim 


| Hash de arquivo | Sim | Sim 


| Número de usuários com acesso | Sim | Sim 


| Permissões de usuário/grupo | Sim | Sim 


| Proprietário do arquivo | Sim | Sim 


| Tipo de diretório | Sim | Sim 
|===
====