---
sidebar: sidebar 
permalink: task-deploy-compliance-dark-site.html 
keywords: cloud compliance, bluexp, data sense, get started, web browser connectivity, cloud compliance access, privacy, linux, ubuntu, compliance, on-premises, dark site, upgrade, private mode, docker, podman, rhel, bluexp classification, classification, install, cloud data sense, linux host 
summary: 'Conclua algumas etapas para instalar o NetApp Data Classification em um host Linux em um site local que não tenha acesso à Internet, também conhecido como "modo privado". Este tipo de instalação é perfeito para seus sites seguros.' 
---
= Instalar o NetApp Data Classification em um host Linux sem acesso à Internet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A instalação do NetApp Data Classification em um host Linux em um site local que não tem acesso à Internet é conhecida como _modo privado_.  Este tipo de instalação, que usa um script de instalação, não tem conectividade com a camada SaaS do NetApp Console .


IMPORTANT: O modo privado BlueXP (interface BlueXP legada) normalmente é usado com ambientes locais que não têm conexão com a Internet e com regiões de nuvem seguras, o que inclui AWS Secret Cloud, AWS Top Secret Cloud e Azure IL6. A NetApp continua a oferecer suporte a esses ambientes com a interface legada BlueXP . Para documentação do modo privado na interface BlueXP legada, consultelink:https://docs.netapp.com/us-en/console-setup-admin/media/BlueXP-Private-Mode-legacy-interface.pdf["Documentação em PDF para o modo privado do BlueXP"^] .
