= Versão 1.44
:allow-uri-read: 




=== Versão 1.44

Esta versão de BlueXP classification inclui:

.Tempos de atualização aprimorados para o painel de governança
Os tempos de atualização para componentes individuais do painel de governança foram melhorados. A tabela a seguir exibe a frequência de atualizações para cada componente.

[cols="1,1"]
|===
| Componente | Horários de atualização 


| Era dos Dados | 24 horas 


| Categorias | 24 horas 


| Visão geral dos dados | 5 minutos 


| Arquivos duplicados | 2 horas 


| Tipos de arquivo | 24 horas 


| Dados não comerciais | 2 horas 


| Permissões abertas | 24 horas 


| Pesquisas salvas | 2 horas 


| Dados sensíveis e permissões amplas | 24 horas 


| Tamanho dos dados | 24 horas 


| Dados obsoletos | 2 horas 


| Principais repositórios de dados por nível de sensibilidade | 2 horas 
|===
Você pode visualizar o horário da última atualização e atualizar manualmente os componentes Arquivos duplicados, Dados não comerciais, Pesquisas salvas, Dados obsoletos e Principais repositórios de dados por nível de sensibilidade. Para obter mais informações sobre o painel de governança, consultelink:https://docs.netapp.com/us-en/data-services-data-classification/task-controlling-governance-data.html["Visualize detalhes de governança sobre os dados armazenados em sua organização"] .

.Melhorias de desempenho e segurança
Foram feitas melhorias para melhorar o desempenho, o consumo de memória e a segurança da classificação BlueXP .

.Correções de bugs
O Redis foi atualizado para melhorar a confiabilidade da BlueXP classification. A BlueXP classification agora usa o Elasticsearch para melhorar a precisão dos relatórios de contagem de arquivos durante as verificações.
