= Versão 1.42
:allow-uri-read: 




=== Versão 1.42

Esta versão de BlueXP classification inclui:

.Digitalização em massa para ambientes de trabalho
A classificação do BlueXP suporta operações em lote para ambientes de trabalho. Você pode optar por ativar verificações de Mapping, ativar verificações de Map & Classify, desativar verificações ou criar uma configuração personalizada em volumes no ambiente de trabalho. Se você fizer uma seleção para um volume individual, ela substituirá a seleção em lote. Para realizar uma operação em lote, acesse a página **Configuração** e faça sua seleção.

.Baixe o relatório de investigação localmente
A BlueXP classification permite baixar relatórios de investigação de dados localmente para visualizar no navegador. Se você escolher a opção local, a investigação de dados estará disponível apenas no formato CSV e exibirá apenas as primeiras 10.000 linhas de dados.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html#create-the-data-investigation-report["Investigue os dados armazenados em sua organização com a BlueXP classification"] .
