= Priorizar varreduras de classificação
:allow-uri-read: 




[[prioritize-classification-scans]]
=== Priorizar varreduras de classificação

A Classificação de Dados permite priorizar varreduras de Map & Classify, além das varreduras somente de Map, possibilitando que você selecione quais varreduras serão concluídas primeiro. A priorização de varreduras de Map & Classify é suportada durante e antes do início das varreduras. Se você optar por priorizar uma varredura enquanto ela estiver em andamento, tanto o mapeamento quanto a classificação das varreduras de Map & Classify serão priorizados.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#prioritize-scans["Priorizar varreduras"] .



[[support-for-canadian-personally-identifiable-information-pii-data-categories]]
=== Suporte para categorias de dados de informações de identificação pessoal (PII) canadenses

As varreduras de classificação de dados identificam categorias de dados PII canadenses. Essas categorias incluem informações bancárias, números de passaporte, números de seguro social, números de carteira de motorista e números de cartão de saúde para todas as províncias e territórios canadenses.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-personal-data["Categorias de dados pessoais"] .



[[custom-classification-preview]]
=== Classificação personalizada (visualização)

A Classificação de Dados oferece suporte a classificações personalizadas para verificações do Map & Classify. Com classificações personalizadas, você pode adaptar as verificações de Classificação de Dados para capturar dados específicos da sua organização usando expressões regulares. Este recurso está atualmente em versão prévia.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["Adicionar classificações personalizadas"] .



[[saved-searches-tab]]
=== Aba de pesquisas salvas

A aba **Políticas** foi renomeadalink:https://docs.netapp.com/us-en/data-services-data-classification/task-using-policies.html["**Pesquisas salvas**"] . A funcionalidade não foi alterada.



[[send-scan-events-to-the-audit-page]]
=== Enviar eventos de verificação para a página de auditoria

A classificação de dados suporta o envio de eventos de classificação (quando uma varredura é iniciada e quando ela termina) para o link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["NetApp Console Página de auditoria"^].



[[security-updates]]
=== Atualizações de segurança

* O pacote Keras foi atualizado, mitigando vulnerabilidades (BDSA-2025-0107 e BDSA-2025-1984).
* A configuração dos contêineres do Docker foi atualizada. O contêiner não tem mais acesso às interfaces de rede do host para criar pacotes de rede brutos. Ao reduzir o acesso desnecessário, a atualização atenua potenciais riscos de segurança.




[[performance-enhancements]]
=== Melhorias de desempenho

Melhorias no código foram implementadas para reduzir o uso de RAM e melhorar o desempenho geral da Classificação de Dados.



[[bug-fixes]]
=== Correções de bugs

Foram corrigidos bugs que causavam falhas nas verificações do StorageGRID , o não carregamento das opções de filtro da página de investigação e o não download da Avaliação de Descoberta de Dados para avaliações de alto volume.
