= Página de configuração aprimorada
:allow-uri-read: 




=== Página de configuração aprimorada

O Data Classification atualizou e aprimorou a página de Configuração, proporcionando uma experiência de usabilidade melhor para gerenciar configurações, sistemas, habilitar verificações e monitorar a integridade do sistema. A nova página de Configuração oferece as funcionalidades existentes em um formato mais fácil de usar, além da possibilidade de filtrar sistemas por tipo, status de erro e status da verificação. A nova página também fornece um resumo dos sistemas conectados e uma visão geral das verificações ativas e configuradas.

Analise um link:https://youtu.be/_8YJ3KyZ7nI["vídeo tutorial"^]. Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Analise fontes de dados com a Classificação de Dados"^].



=== Função de administrador de conformidade IAM

A Classificação de Dados agora oferece suporte a uma função de administrador de Conformidade para gerenciar permissões na Classificação de Dados. A função de administrador de Conformidade não tem acesso a recursos como agentes do Console e espaços de trabalho. Usuários com a função de administrador de Conformidade devem estar associados a pelo menos uma outra função.

Ao instalar o Data Classification, você deve ter a função de administrador da plataforma Console ou a função de administrador de Compliance.

Se você já é um usuário, o acesso deve continuar normalmente. Por exemplo, uma função na plataforma que possui uma função de administrador de pasta ou projeto já tem acesso.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Funções de classificação de dados"^].



=== Implantar o NetApp Data Classification com OVA

NetApp Data Classification agora oferece suporte à implantação com VMware Open Virtual Appliance (OVA), proporcionando uma estratégia de implantação simplificada para ambientes VMware vSphere locais.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Implantar o NetApp Data Classification com OVA"^].
